TEST_CASES = [
    {
        "name": "Low delay risk",
        "payment_delay_probability": 0.05,
        "contract_value": 30000,
        "cash_reserve": 50000,
        "monthly_cost": 10000,
        "upfront_pct": 0.20,
        "payment_terms_days": 30,
    },
    {
        "name": "Medium delay risk",
        "payment_delay_probability": 0.50,
        "contract_value": 30000,
        "cash_reserve": 50000,
        "monthly_cost": 10000,
        "upfront_pct": 0.20,
        "payment_terms_days": 30,
    },
    {
        "name": "High delay risk",
        "payment_delay_probability": 0.95,
        "contract_value": 30000,
        "cash_reserve": 50000,
        "monthly_cost": 10000,
        "upfront_pct": 0.20,
        "payment_terms_days": 30,
    },
    {
        "name": "Large contract",
        "payment_delay_probability": 0.50,
        "contract_value": 120000,
        "cash_reserve": 45000,
        "monthly_cost": 25000,
        "upfront_pct": 0.20,
        "payment_terms_days": 60,
    },
    {
        "name": "Strong upfront protection",
        "payment_delay_probability": 0.50,
        "contract_value": 120000,
        "cash_reserve": 45000,
        "monthly_cost": 25000,
        "upfront_pct": 0.70,
        "payment_terms_days": 30,
    },
]